[package]
name = "apollo-dctdst-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Direct scalar DCT-III kernels"
readme = "README.md"

[dependencies]
eunomia.workspace = true

[lints]
workspace = true
