"""Typed public surface for the Apollo FFT bindings."""

from typing import Any, Dict, List, Literal, Optional

import numpy as np
from numpy.typing import NDArray

Precision = Literal["high_accuracy", "low_precision", "mixed_precision"]
Array = NDArray[Any]
RealArray = NDArray[np.floating[Any]]
ComplexArray = NDArray[np.complexfloating[Any, Any]]


class FftPlan1D:
    def __init__(self, n: int, precision: Optional[Precision] = ...) -> None: ...
    def fft(self, input: Array) -> Array: ...
    def ifft(self, input: Array) -> Array: ...
    def fft_complex(self, input: ComplexArray) -> ComplexArray: ...
    def ifft_complex(self, input: ComplexArray) -> ComplexArray: ...


class FftPlan2D:
    def __init__(self, nx: int, ny: int, precision: Optional[Precision] = ...) -> None: ...
    def fft(self, input: Array) -> Array: ...
    def ifft(self, input: Array) -> Array: ...
    def fft_complex(self, input: ComplexArray) -> ComplexArray: ...
    def ifft_complex(self, input: ComplexArray) -> ComplexArray: ...


class FftPlan3D:
    def __init__(self, nx: int, ny: int, nz: int, precision: Optional[Precision] = ...) -> None: ...
    def fft(self, input: Array) -> Array: ...
    def ifft(self, input: Array) -> Array: ...
    def rfft(self, input: RealArray) -> ComplexArray: ...
    def irfft(self, input: ComplexArray) -> RealArray: ...


def available_backends() -> List[str]: ...
def backend_capabilities() -> Dict[str, Dict[str, Any]]: ...

def fft1(input: Array, precision: Optional[Precision] = ...) -> Array: ...
def ifft1(input: Array, precision: Optional[Precision] = ...) -> Array: ...
def fft2(input: Array, precision: Optional[Precision] = ...) -> Array: ...
def ifft2(input: Array, precision: Optional[Precision] = ...) -> Array: ...
def fft3(input: Array, precision: Optional[Precision] = ...) -> Array: ...
def ifft3(input: Array, precision: Optional[Precision] = ...) -> Array: ...
def rfft3(input: RealArray) -> ComplexArray: ...
def irfft3(input: ComplexArray, nz: int) -> RealArray: ...

def fft_complex1(input: ComplexArray) -> ComplexArray: ...
def ifft_complex1(input: ComplexArray) -> ComplexArray: ...
def fft_complex2(input: ComplexArray) -> ComplexArray: ...
def ifft_complex2(input: ComplexArray) -> ComplexArray: ...
def fft_complex3(input: ComplexArray) -> ComplexArray: ...
def ifft_complex3(input: ComplexArray) -> ComplexArray: ...

def fftfreq(n: int, d: float = ...) -> NDArray[np.float64]: ...
def rfftfreq(n: int, d: float = ...) -> NDArray[np.float64]: ...
def fftshift(input: RealArray) -> RealArray: ...
def ifftshift(input: RealArray) -> RealArray: ...

def nufft_type1_1d(
    positions: RealArray,
    values: ComplexArray,
    dx: float,
    n_out: Optional[int] = ...,
) -> ComplexArray: ...
def nufft_type2_1d(
    fourier_coeffs: ComplexArray, positions: RealArray, dx: float
) -> ComplexArray: ...
def nufft_type1_3d(
    positions: RealArray,
    values: ComplexArray,
    nx: int,
    ny: int,
    nz: int,
    dx: float,
    dy: float,
    dz: float,
) -> ComplexArray: ...
def nufft_type1_1d_fast(
    positions: RealArray,
    values: ComplexArray,
    dx: float,
    n_out: Optional[int] = ...,
    kernel_width: int = ...,
) -> ComplexArray: ...
def nufft_type2_1d_fast(
    fourier_coeffs: ComplexArray,
    positions: RealArray,
    dx: float,
    kernel_width: int = ...,
) -> ComplexArray: ...
def nufft_type1_3d_fast(
    positions: RealArray,
    values: ComplexArray,
    nx: int,
    ny: int,
    nz: int,
    dx: float,
    dy: float,
    dz: float,
    kernel_width: int = ...,
) -> ComplexArray: ...

def dht1(input: RealArray) -> RealArray: ...
def idht1(input: RealArray) -> RealArray: ...
def dht2(input: RealArray) -> RealArray: ...
def idht2(input: RealArray) -> RealArray: ...
def dht3(input: RealArray) -> RealArray: ...
def idht3(input: RealArray) -> RealArray: ...

def fwht1(input: RealArray) -> RealArray: ...
def ifwht1(input: RealArray) -> RealArray: ...
def fwht2(input: RealArray) -> RealArray: ...
def ifwht2(input: RealArray) -> RealArray: ...
def fwht3(input: RealArray) -> RealArray: ...
def ifwht3(input: RealArray) -> RealArray: ...

def dct2_1d(input: RealArray) -> RealArray: ...
def idct2_1d(input: RealArray) -> RealArray: ...
def dst2_1d(input: RealArray) -> RealArray: ...
def idst2_1d(input: RealArray) -> RealArray: ...

__version__: str
__all__: List[str]
