#[cfg(target_arch = "x86_64")]
pub(crate) mod avx512_backend;
#[cfg(target_arch = "x86_64")]
pub(crate) mod backend_impl;
pub(crate) mod base;
pub(crate) mod fixed;
pub(crate) mod pair;
pub(crate) mod quad;
pub(crate) mod triple_1;
pub(crate) mod triple_2;
